"突出显示当前行，有一个横线
set cursorline
" 在编辑过程中，在右下角显示光标位置的状态行
set ruler

"智能对齐方式,当你写完for循环的右括号时，按enter键会以代码对齐方式自动对齐 
set smartindent
"开启自动缩进,自动对齐
set autoindent
" 使得按退格键时可以一次删掉 4 个空格
set softtabstop=4

"缩进尺寸为4个空格
set sw=4
" 设定 tab 长度为 4
set tabstop=4
" 换行时行间交错使用4个空格 
set shiftwidth=4

"编辑时将所有tab替换为空格
set et
set expandtab

"vim内部编码
set encoding=utf-8
"当前编辑的文件代码
set fileencoding=utf-8

"设置匹配模式，类似当输入一个左括号时会匹配相应的那个右括号.在输入括号时光标会短暂地跳到与之相匹配的括号处
set showmatch
" 禁止在搜索到文件两端时重新搜索
"set nowrapscan
"显示行号
set number
"语法高亮

" 搜索时忽略大小写，但在有一个或以上大写字母时仍保持对大小写敏感
set ignorecase smartcase
" 输入搜索内容时就显示搜索结果
set incsearch    
" 搜索时高亮显示被找到的文本
set hlsearch            
       
syntax on

imap { {}<ESC>i<CR><ESC>V<O
imap ( ()<ESC>i
imap [ []<ESC>i
inoremap " ""<ESC>i
inoremap ' ''<ESC>i
""imap p <?php?><ESC>HHi<CR>V<O
ab /* /**/

"ctrl+p加 // 注释
map  I//<ESC>
"去掉//
map  0xx<ESC> 

autocmd FileType php set omnifunc=phpcomplete#CompletePHP
filetype plugin on


