" All system-wide defaults are set in $VIMRUNTIME/debian.vim (usually just
" /usr/share/vim/vimcurrent/debian.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vim/vimrc), since debian.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing debian.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
runtime! debian.vim

" Uncomment the next line to make Vim more Vi-compatible
" NOTE: debian.vim sets 'nocompatible'.  Setting 'compatible' changes numerous
" options, so any other options should be set AFTER setting 'compatible'.
"set compatible

" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.
if has("syntax")
  syntax on
endif

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
"set background=dark

" Uncomment the following to have Vim jump to the last position when
" reopening a file
"if has("autocmd")
"  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
"endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
"if has("autocmd")
"  filetype plugin indent on
"endif

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
"set showcmd		" Show (partial) command in status line.
"set showmatch		" Show matching brackets.
"set ignorecase		" Do case insensitive matching
"set smartcase		" Do smart case matching
"set incsearch		" Incremental search
"set autowrite		" Automatically save before commands like :next and :make
"set hidden             " Hide buffers when they are abandoned
"set mouse=a		" Enable mouse usage (all modes)

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

"突出显示当前行，有一个横线
set cursorline
" 在编辑过程中，在右下角显示光标位置的状态行
set ruler

"智能对齐方式,当你写完for循环的右括号时，按enter键会以代码对齐方式自动对齐 
set smartindent
"开启自动缩进,自动对齐
set autoindent
" 使得按退格键时可以一次删掉 4 个空格
set softtabstop=4

"缩进尺寸为4个空格
set sw=4
" 设定 tab 长度为 4
set tabstop=4
" 换行时行间交错使用4个空格 
set shiftwidth=4

"编辑时将所有tab替换为空格
set et
set expandtab

"vim内部编码
set encoding=utf-8
"当前编辑的文件代码
set fileencoding=utf-8

"设置匹配模式，类似当输入一个左括号时会匹配相应的那个右括号.在输入括号时光标会短暂地跳到与之相匹配的括号处
set showmatch
" 禁止在搜索到文件两端时重新搜索
"set nowrapscan
"显示行号
set number
"语法高亮

" 搜索时忽略大小写，但在有一个或以上大写字母时仍保持对大小写敏感
set ignorecase smartcase
" 输入搜索内容时就显示搜索结果
set incsearch    
" 搜索时高亮显示被找到的文本
set hlsearch            
       
syntax on

imap { {}<ESC>i<CR><ESC>V<O
imap ( ()<ESC>i
imap [ []<ESC>i
inoremap " ""<ESC>i
inoremap ' ''<ESC>i
""imap p <?php?><ESC>HHi<CR>V<O
ab /* /**/

autocmd FileType php set omnifunc=phpcomplete#CompletePHP
filetype plugin on


